""" Labels """
FAKE = 1
REAL = 0
ABSTAIN = -1

"""

Stylistic thresholds

"""

# exclamation marks
CONTENT_EXCLAMATION_UPPER = 42
CONTENT_EXCLAMATION_LOWER = 1

CONTENT_EXCLAMATION_RATIO_UPPER = 1.0
CONTENT_EXCLAMATION_RATIO_LOWER = 0.0

TITLE_EXCLAMATION_UPPER = 6
TITLE_EXCLAMATION_LOWER = 4

TITLE_EXCLAMATION_RATIO_UPPER = 0.163
TITLE_EXCLAMATION_RATIO_LOWER = 0.0043


# word count
CONTENT_WORD_COUNT_UPPER = 643
CONTENT_WORD_COUNT_LOWER = 188

TITLE_WORD_COUNT_UPPER = 13
TITLE_WORD_COUNT_LOWER = 3


# sentence count
CONTENT_SENTENCE_COUNT_UPPER = 29
CONTENT_SENTENCE_COUNT_LOWER = 10

TITLE_SENTENCE_COUNT_UPPER = 7
TITLE_SENTENCE_COUNT_LOWER = 1


# url count
CONTENT_URL_COUNT_UPPER = 50
CONTENT_URL_COUNT_LOWER = 0


# quote count
CONTENT_QUOTE_COUNT_UPPER = 12
CONTENT_QUOTE_COUNT_LOWER = 0

CONTENT_QUOTE_RATIO_UPPER = 0.021
CONTENT_QUOTE_RATIO_LOWER = 0


# stop words
CONTENT_STOP_WORD_COUNT_UPPER = 267
CONTENT_STOP_WORD_COUNT_LOWER = 78

CONTENT_STOP_WORD_RATIO_UPPER = 0.8
CONTENT_STOP_WORD_RATIO_LOWER = 0

TITLE_STOP_WORD_COUNT_UPPER = 7
TITLE_STOP_WORD_COUNT_LOWER = 2

TITLE_STOP_WORD_RATIO_UPPER = 0.46
TITLE_STOP_WORD_RATIO_LOWER = 0.166


# capital words
CONTENT_CAPITAL_WORD_COUNT_UPPER = 5
CONTENT_CAPITAL_WORD_COUNT_LOWER = 0

CONTENT_CAPITAL_WORD_RATIO_UPPER = 0.013
CONTENT_CAPITAL_WORD_RATIO_LOWER = 0.0031

TITLE_CAPITAL_WORD_COUNT_UPPER = 0
TITLE_CAPITAL_WORD_COUNT_LOWER = 0

TITLE_CAPITAL_WORD_RATIO_UPPER = 0.0715
TITLE_CAPITAL_WORD_RATIO_LOWER = 0


"""

Complexity thresholds

"""


# ttr score
CONTENT_TTR_SCORE_FAKE_UPPER = 0.95
CONTENT_TTR_SCORE_FAKE_MID_UPPER = 0.83
CONTENT_TTR_SCORE_FAKE_MID_LOWER = 0.38
CONTENT_TTR_SCORE_FAKE_LOWER = 0.25

CONTENT_TTR_SCORE_REAL_UPPER = 0.55
CONTENT_TTR_SCORE_REAL_LOWER = 0.44

TITLE_TTR_SCORE_UPPER = 1
TITLE_TTR_SCORE_LOWER = 0


# words per sentence
CONTENT_WORDS_PER_SENTENCE_UPPER = 35
CONTENT_WORDS_PER_SENTENCE_LOWER = 5


# word length
CONTENT_AVG_WORD_LENGTH_FAKE_UPPER = 4.89
CONTENT_AVG_WORD_LENGTH_FAKE_MID_UPPER = 5.7
CONTENT_AVG_WORD_LENGTH_FAKE_MID = 3.8
CONTENT_AVG_WORD_LENGTH_FAKE_LOWER = 2

CONTENT_AVG_WORD_LENGTH_REAL_UPPER = 5.832
CONTENT_AVG_WORD_LENGTH_REAL_MID = 4.40
CONTENT_AVG_WORD_LENGTH_REAL_LOWER = 4

TITLE_AVG_WORD_LENGTH_UPPER = 7.5
TITLE_AVG_WORD_LENGTH_MID = 5.4
TITLE_AVG_WORD_LENGTH_LOWER = 5


# word length no stopwords

CONTENT_AVG_WORD_LENGTH_NO_STOP_WORDS_FAKE_UPPER = 6.6
CONTENT_AVG_WORD_LENGTH_NO_STOP_WORDS_FAKE_MID = 4
CONTENT_AVG_WORD_LENGTH_NO_STOP_WORDS_FAKE_LOWER = 2

CONTENT_AVG_WORD_LENGTH_NO_STOP_WORDS_REAL_UPPER = 6.3
CONTENT_AVG_WORD_LENGTH_NO_STOP_WORDS_REAL_LOWER = 4.5

TITLE_AVG_WORD_LENGTH_NO_STOP_WORDS_UPPER = 1
TITLE_AVG_WORD_LENGTH_NO_STOP_WORDS_LOWER = 4.53


"""

Sentiment thresholds

"""

# content sentence sentiment
CONTENT_SENTIMENT_SENTENCE_NEG_UPPER = 0.36
CONTENT_SENTIMENT_SENTENCE_NEG_LOWER = 0.21

CONTENT_SENTIMENT_SENTENCE_POS_UPPER = 0.79
CONTENT_SENTIMENT_SENTENCE_POS_LOWER = 0.64

CONTENT_SENTIMENT_SENTENCE_SUB_UPPER = 0.37
CONTENT_SENTIMENT_SENTENCE_SUB_LOWER = 0.25


# content text sentiment
CONTENT_SENTIMENT_TEXT_NEG_UPPER = 0.000067
CONTENT_SENTIMENT_TEXT_NEG_LOWER = 0

CONTENT_SENTIMENT_TEXT_POS_UPPER = 1
CONTENT_SENTIMENT_TEXT_POS_LOWER = 0.999945

CONTENT_SENTIMENT_TEXT_SUB_UPPER = 0.467
CONTENT_SENTIMENT_TEXT_SUB_LOWER = 0.355


# content word sentiment
CONTENT_SENTIMENT_WORD_NEG_UPPER = 1
CONTENT_SENTIMENT_WORD_NEG_LOWER = 0

CONTENT_SENTIMENT_WORD_POS_UPPER = 1
CONTENT_SENTIMENT_WORD_POS_LOWER = 0

CONTENT_SENTIMENT_WORD_SUB_UPPER = 0.039
CONTENT_SENTIMENT_WORD_SUB_LOWER = 0.025


# title sentence sentiment
TITLE_SENTIMENT_SENTENCE_NEG_UPPER = 0.537
TITLE_SENTIMENT_SENTENCE_NEG_LOWER = 0.115

TITLE_SENTIMENT_SENTENCE_POS_UPPER = 1
TITLE_SENTIMENT_SENTENCE_POS_LOWER = 0

TITLE_SENTIMENT_SENTENCE_SUB_UPPER = 0.45
TITLE_SENTIMENT_SENTENCE_SUB_LOWER = 0


# title text sentiment
TITLE_SENTIMENT_TEXT_NEG_UPPER = 1
TITLE_SENTIMENT_TEXT_NEG_LOWER = 0

TITLE_SENTIMENT_TEXT_POS_UPPER = 1
TITLE_SENTIMENT_TEXT_POS_LOWER = 0

TITLE_SENTIMENT_TEXT_SUB_UPPER = 0.45
TITLE_SENTIMENT_TEXT_SUB_LOWER = 0


# title word sentiment
TITLE_SENTIMENT_WORD_NEG_UPPER = 0.799
TITLE_SENTIMENT_WORD_NEG_LOWER = 0.138

TITLE_SENTIMENT_WORD_POS_UPPER = 0.86
TITLE_SENTIMENT_WORD_POS_LOWER = 0.2

TITLE_SENTIMENT_WORD_SUB_UPPER = 1
TITLE_SENTIMENT_WORD_SUB_LOWER = 0


"""

POS Thresholds

"""


# adjectives
CONTENT_ADJECTIVE_RATIO_UPPER = 0.113
CONTENT_ADJECTIVE_RATIO_LOWER = 0.038

TITLE_ADJECTIVE_RATIO_UPPER = 0.308
TITLE_ADJECTIVE_RATIO_LOWER = 0


# personal pronouns
CONTENT_PERSONAL_PRONOUNS_COUNT_UPPER = 51
CONTENT_PERSONAL_PRONOUNS_COUNT_LOWER = 1

CONTENT_PERSONAL_PRONOUNS_RATIO_UPPER = 0.07
CONTENT_PERSONAL_PRONOUNS_RATIO_LOWER = 0


# verbs
CONTENT_VERB_RATIO_UPPER = 0.21694
CONTENT_VERB_RATIO_LOWER = 0.02

TITLE_VERB_RATIO_UPPER = 0.318
TITLE_VERB_RATIO_LOWER = 0.07

CONTENT_PAST_TENSE_VERB_RATIO_UPPER = 0.0832
CONTENT_PAST_TENSE_VERB_RATIO_MID = 0.031
CONTENT_PAST_TENSE_VERB_RATIO_LOWER = 0.0056

TITLE_PAST_TENSE_VERB_RATIO_UPPER = 0.143
TITLE_PAST_TENSE_VERB_RATIO_LOWER = 0

CONTENT_PAST_TENSE_VERB_OF_ALL_VERBS_RATIO_UPPER = 0.48
CONTENT_PAST_TENSE_VERB_OF_ALL_VERBS_RATIO_MID = 0.4
CONTENT_PAST_TENSE_VERB_OF_ALL_VERBS_RATIO_LOWER = 0.2

TITLE_PAST_TENSE_VERB_OF_ALL_VERBS_RATIO_UPPER = 1
TITLE_PAST_TENSE_VERB_OF_ALL_VERBS_RATIO_LOWER = 0


# nouns
TITLE_NOUNS_COUNT_UPPER = 8
TITLE_NOUNS_COUNT_LOWER = 7

TITLE_NOUNS_RATIO_UPPER = 1
TITLE_NOUNS_RATIO_LOWER = 0.632


# proper nouns
TITLE_PROPER_NOUNS_COUNT_UPPER = 6
TITLE_PROPER_NOUNS_COUNT_LOWER = 6

TITLE_PROPER_NOUNS_RATIO_UPPER = 0.46
TITLE_PROPER_NOUNS_RATIO_LOWER = 0.46
